export const body_question_list = [
  {
    type: 'input',
    label: '이름',
    placeholder: '임보 동물 이름 입력',
    name: 'name',
    isRequired: true,
    maxLength: 20,
  },
  {
    type: 'buttons',
    name: 'protectionType',
    title: '임보 종류',
    caseA: '일반',
    caseB: '긴급',
    description:
      '* 긴급 임보는 1주일 이후에 보호소로 보내지는 경우에 선택 해주세요.',
  },
  {
    type: 'buttons',
    name: 'species',
    title: '임보동물 종류',
    caseA: '강아지',
    caseB: '고양이',
  },
  {
    type: 'input',
    label: '품종',
    placeholder: '품종을 입력해주세요',
    name: 'breed',
    isRequired: true,
    maxLength: 30,
  },
  {
    type: 'buttons',
    name: 'gender',
    title: '성별',
    caseA: '여아',
    caseB: '남아',
  },
  {
    type: 'buttons',
    name: 'isNeutered',
    title: '중성화 수술 여부',
    caseA: '했어요',
    caseB: '안했어요',
  },
  {
    type: 'vaccination',
  },
  {
    type: 'input',
    label: '구조지역',
    placeholder: '어디서 구조했나요?',
    name: 'rescueLocation',
    isRequired: true,
    maxLength: 200,
  },
  {
    type: 'input',
    label: '나이',
    placeholder: '임보 동물의 나이를 입력해주세요',
    name: 'age',
    isRequired: true,
    maxLength: 20,
  },
  {
    type: 'input',
    label: '몸무게',
    placeholder: '예) 32 (kg)',
    name: 'weight',
    isRequired: true,
    maxLength: 20,
  },
  {
    type: 'textarea',
    label: '정보',
    placeholder: '현재상황 및 임보동물에 대한 이야기 모두 좋아요',
    name: 'info',
    isRequired: true,
    maxLength: 300,
  },
];
